#!/bin/sh
ZEF_DATE="`date`"

./cpkernel && \
cd ../stockVC_kernel_ramdisk && \
../mkoptinitrd && \
cd ../buildboot && \
./mkbootimg.sh

cd /home/zefie/optimusdev/optimus/kernel_updatezip_template
rm /home/zefie/optimusdev/optimus/kernel_updatezip_template/kernel/boot.img
rm /home/zefie/optimusdev/optimus/kernel_updatezip_template/kernel/zImage
cp /media/dropbox/boot.img /home/zefie/optimusdev/optimus/kernel_updatezip_template/kernel/boot.img
rm META-INF/com/google/android/updater-script

echo "ui_print(\"Extracting System Files...\");" >> META-INF/com/google/android/updater-script
echo "set_progress(1.000000);" >> META-INF/com/google/android/updater-script
echo "mount(\"MTD\", \"system\", \"/system\");" >> META-INF/com/google/android/updater-script
echo "package_extract_dir(\"system\", \"/system\");" >> META-INF/com/google/android/updater-script
echo "unmount(\"/system\");" >> META-INF/com/google/android/updater-script
echo "package_extract_dir(\"kernel\", \"/tmp\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"Installing kernel...\");" >> META-INF/com/google/android/updater-script
echo "write_raw_image(\"/tmp/boot.img\", \"boot\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"*-* Xionia Kernel *-*\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"-------------------\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"Generated on:\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"$ZEF_DATE\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"-------------------\");" >> META-INF/com/google/android/updater-script
echo "ui_print(\"Done!\");" >> META-INF/com/google/android/updater-script

zip -9rq /tmp/kernel.zip *

rm /media/dropbox/xionia.zip
java -jar /home/zefie/optimusdev/optimus/java/signapk.jar /home/zefie/optimusdev/optimus/java/testkey.x509.pem /home/zefie/optimusdev/optimus/java/testkey.pk8 /tmp/kernel.zip /media/dropbox/xionia.zip
rm /tmp/kernel.zip
ls -l /media/dropbox/xionia.zip
