#!/bin/sh
rm ../buildboot/zImage
cp arch/arm/boot/zImage ../buildboot/
cp arch/arm/boot/zImage ../kernel_updatezip_template/kernel/

rm ../ramdisk/lib/modules/*
cp drivers/net/tun.ko ../ramdisk/lib/modules/
cp drivers/net/wireless/bcm4325/wireless.ko ../ramdisk/lib/modules/
cp arch/arm/mach-msm/dma_test.ko ../ramdisk/lib/modules/
cp net/ipv4/tcp_bic.ko ../ramdisk/lib/modules/
cp net/ipv4/tcp_htcp.ko ../ramdisk/lib/modules/
cp net/ipv4/tcp_westwood.ko ../ramdisk/lib/modules/


rm ../ramdisk_public/lib/modules/*
cp drivers/net/tun.ko ../ramdisk_public/lib/modules/
cp drivers/net/wireless/bcm4325/wireless.ko ../ramdisk_public/lib/modules/
cp arch/arm/mach-msm/dma_test.ko ../ramdisk_public/lib/modules/
cp net/ipv4/tcp_bic.ko ../ramdisk_public/lib/modules/
cp net/ipv4/tcp_htcp.ko ../ramdisk_public/lib/modules/
cp net/ipv4/tcp_westwood.ko ../ramdisk_public/lib/modules/

rm ../kernel_updatezip_template/system/lib/modules/*
cp ../ramdisk/lib/modules/* ../kernel_updatezip_template/system/lib/modules/

