#!/bin/sh
rm -r ../buildboot/zImage
cp arch/arm/boot/zImage ../buildboot/

# Gingerbread 
mkdir ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/
mkdir ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/

cp drivers/net/wireless/bcm4325/wireless.ko ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/
cp drivers/net/tun.ko ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/
cp arch/arm/mach-msm/dma_test.ko ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/
cp net/ipv4/tcp_bic.ko ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/
cp net/ipv4/tcp_htcp.ko ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/
cp net/ipv4/tcp_westwood.ko ../../cyanogen/gingerbread/out/target/product/thunderc/root/lib/modules/

cp drivers/net/wireless/bcm4325/wireless.ko ../../cyanogen/gingerbread/device/lge/thunderc/files/
cp arch/arm/mach-msm/dma_test.ko ../../cyanogen/gingerbread/device/lge/thunderc/files/
cp net/ipv4/tcp_bic.ko ../../cyanogen/gingerbread/device/lge/thunderc/files/
cp net/ipv4/tcp_htcp.ko ../../cyanogen/gingerbread/device/lge/thunderc/files/
cp net/ipv4/tcp_westwood.ko ../../cyanogen/gingerbread/device/lge/thunderc/files/
cp drivers/net/tun.ko ../../cyanogen/gingerbread/device/lge/thunderc/files/
cp arch/arm/boot/zImage ../../cyanogen/gingerbread/device/lge/thunderc/files/


# Froyo 
mkdir ../../cyanogen/froyo/out/target/product/thunderc/root/lib/
mkdir ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/

cp drivers/net/wireless/bcm4325/wireless.ko ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/
cp drivers/net/tun.ko ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/
cp arch/arm/mach-msm/dma_test.ko ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/
cp net/ipv4/tcp_bic.ko ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/
cp net/ipv4/tcp_htcp.ko ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/
cp net/ipv4/tcp_westwood.ko ../../cyanogen/froyo/out/target/product/thunderc/root/lib/modules/

cp drivers/net/wireless/bcm4325/wireless.ko ../../cyanogen/froyo/device/lge/thunderc/files/
cp arch/arm/mach-msm/dma_test.ko ../../cyanogen/froyo/device/lge/thunderc/files/
cp net/ipv4/tcp_bic.ko ../../cyanogen/froyo/device/lge/thunderc/files/
cp net/ipv4/tcp_htcp.ko ../../cyanogen/froyo/device/lge/thunderc/files/
cp net/ipv4/tcp_westwood.ko ../../cyanogen/froyo/device/lge/thunderc/files/
cp drivers/net/tun.ko ../../cyanogen/froyo/device/lge/thunderc/files/
cp arch/arm/boot/zImage ../../cyanogen/froyo/device/lge/thunderc/files/


