#!/bin/sh
rm ../buildboot/zImage
cp arch/arm/boot/zImage ../buildboot/

mkdir ../ramdisk_cyanogen-ginger/lib/ 
mkdir ../ramdisk_cyanogen-ginger/lib/modules 
cp drivers/net/wireless/bcm4325/wireless.ko ../ramdisk_cyanogen-ginger/lib/modules/
cp drivers/net/tun.ko ../ramdisk_cyanogen-ginger/lib/modules/


